eth:
  - 'table_3'
rgbdtum:
  - 'rgbd_dataset_freiburg1_xyz'
  - 'rgbd_dataset_freiburg3_structure_texture_far'
  - 'rgbd_dataset_freiburg3_long_office_household'
  - 'rgbd_dataset_freiburg2_desk'
euroc:
  - MH_01_easy
kitti:
 - '04'
replica:
 - 'office0'
 - 'room0'
7scenes:
 - 'redkitchen_seq-01'
