eth:
  - 'table_3'
# rgbdtum:
#   - 'rgbd_dataset_freiburg1_xyz'
# replica:
#   - 'office0'
# nuim:
#   - 'traj0_frei_png'
# tartanair:
#   - 'ME000'
# euroc:
#   - MH_01_easy
# kitti:
#  - '04'
# ut_coda:
#   - '0'
# rover_t265:
#   - 'campus_small_autumn_t265'
# rover_d435i:
#   - 'campus_small_autumn_d435i'
# rover_picam:
#   - 'campus_small_autumn_picam'
# s3li:
#   - 'vegetation'
# msd:
#   - 'MIO07_mapping_easy'
# sesoko:
#   - ssk16
#   - ssk17
#   - ssk18

  
# sweetcorals:
# - '_indonesia_tabuhan_p1_20250210'

#openloris:
#   - cafe1-1
  # - cafe1-2
  #- market1-1
  # - market1-2
  # - market1-3

# madmax:
#   - A-0

#hilti2022:
  #- exp04_construction_upper_level
  #- exp05_construction_upper_level_2
  #- exp06_construction_upper_level_3
#  - exp14_basement_2
  #- exp16_attic_to_upper_gallery_2
  #- exp18_corridor_lower_gallery_2
# antarctica:
  # - 'DJI_202401111904_001'
  # - 'DJI_202401111932_002'
#  - 'DJI_202401111932_003'
#  - 'DJI_202401112014_004'

#yandiwanba:
  #- 'test1'
#  - 'test4'
#lizardisland:
#  - 'LIRS_FEB1'

#monotum:
#  - 'sequence_01'
#7scenes
#  - 'redkitchen_seq-01'
#  - 'heads_seq-01'