exp_droidslam_dev_mono:
  Config: config_debug.yaml
  NumRuns: 3
  Parameters: {verbose: 1, rgb_idx: [0,100], mode: rgbd}
  Module: droidslam-dev

# exp_okivs2_mono:
#   Config: config_debug.yaml
#   NumRuns: 3
#   Parameters: {verbose: 1, rgb_idx: [0,100], mode: mono-vi}
#   Module: okvis2