exp_orbslam2_mono_vslamlabbench:
  Config: config_vslamlabbench.yaml
  NumRuns: 10
  Parameters: {verbose: 0}
  Module: orbslam2

exp_droidslam_mono_vslamlabbench:
  Config: config_vslamlabbench.yaml
  NumRuns: 10
  Parameters: {verbose: 0}
  Module: droidslam-dev

exp_anyfeature_mono_vslamlabbench_16_11_2025:
  Config: config_vslamlabbench.yaml
  NumRuns: 10
  Parameters: {verbose: 0}
  Module: anyfeature-dev  